### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by TacoScheltema** [xolphin/WHMCS-SSL-Module#1]
Hi, great to see there is some work going towards a module for Xolphin, Would it be possible to add a few lines of documentation on how to install it?

Thanks!
Taco

**Comment by xolphin** [comment]
Hi Taco,

I have updated the readme with a bit of documentation. Please let us know if you run into any issues.

Maarten

**Comment by TacoScheltema** [comment]
Hi Maarten,

Any chance you could use the ioncube 5.4 instead of the 5.5 module? we can't update just yet but I would really like to try this module.

Thanks,
Taco
